name: Testing
on:
    workflow_dispatch:
    pull_request:

concurrency:
    group: reporting-${{ github.ref }}
    cancel-in-progress: true

jobs:
    lint:
        uses: ./.github/workflows/lint.yml
    coverage:
        needs: [lint]
        name: Coverage Reporting
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: ['8.2', '8.3']
                composer:
                    ['2.0', '2.1', '2.2', '2.3', '2.4', '2.5', '2.6', '2.7']
                symfony: ['^6.0', '^7.0']
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.3
                  tools: composer
                  extensions: curl, zip
            - run: composer install
            - run: composer test >> "${GITHUB_STEP_SUMMARY}"
            - uses: clearlyip/code-coverage-report-action@v5
              if: ${{ github.actor != 'dependabot[bot]'}}
              id: code_coverage_report_action
              with:
                  filename: 'output/coverage/cov.xml'
                  fail_on_negative_difference: true
                  artifact_download_workflow_names: 'coverage,cron'
                  overall_coverage_fail_threshold: '30'
                  file_coverage_error_min: '30'
                  file_coverage_warning_max: '75'
            - name: Add Coverage PR Comment
              uses: marocchino/sticky-pull-request-comment@v2
              if: steps.code_coverage_report_action.outputs.file != '' && github.event_name == 'pull_request' && (success() || failure())
              with:
                  recreate: true
                  path: code-coverage-results.md
