name: 'cron'
on:
    workflow_dispatch:
    schedule:
        - cron: '0 0 1 * *'

concurrency:
    group: ${{ github.ref }}
    cancel-in-progress: true

jobs:
    cron:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: shivammathur/setup-php@v2
              with:
                  tools: composer
                  extensions: curl, zip
            - name: Composer Install
              run: composer install
            - name: Test
              run: composer test >> "${GITHUB_STEP_SUMMARY}"
            - uses: clearlyip/code-coverage-report-action@v5
              with:
                  filename: 'app/output/coverage/cov.xml'
