name: Testing
on:
    workflow_dispatch:
    pull_request:
    push:
        branches:
            - master

concurrency:
    group: test-${{ github.ref }}
    cancel-in-progress: true

jobs:
    lint:
        uses: ./.github/workflows/lint.yml
    tests:
        needs: [lint]
        name: Matrix Testing
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: ['8.2', '8.3']
                composer:
                    ['2.0', '2.1', '2.2', '2.3', '2.4', '2.5', '2.6', '2.7']
                symfony: ['^6.0', '^7.0']
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: 'Unit testing'
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  tools: composer:${{ matrix.composer }}
                  extensions: curl, zip
            - run: composer require "symfony/finder:${{ matrix.symfony }}" "symfony/filesystem:${{ matrix.symfony }}"
            - run: composer install
            - run: composer test
    coverage:
        needs: [tests]
        name: Coverage
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - uses: shivammathur/setup-php@v2
              with:
                  tools: composer
                  extensions: curl, zip
            - run: composer install
            - run: composer test >> "${GITHUB_STEP_SUMMARY}"
            - uses: clearlyip/code-coverage-report-action@v5
              with:
                  filename: 'output/coverage/cov.xml'
